### ISSUE TITLE
Variable not defined "localdir"

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-lizsync-plugin#3]
I haven't run my tool yet, I just found it randomly.

In `lizsync/processing/algorithms/synchronize_media_subfolder_to_ftp.py`:

```python
        if not localdir or not os.path.isdir(localdir):
            m = tr('QGIS project local directory not found')
            return returnError(output, m, feedback)
        else:
            m = tr('QGIS project local directory ok')
```

`localdir` is not defined, this will raise an error on runtime.
Minor thing, `m` is not used.

There is another variable `localdir` just a few lines below, but not sure what to do ;-)

**Comment by mdouchin** [comment]
hum... I will have a look. Thanks
